### ISSUE TITLE
Sunny breaks dashboard 'click to toggle' functionality

### ISSUE THREAD

**Issue by thewebists** [TypistTech/sunny#1]
I've just spotted an issue on two separate projects where I've recently installed Sunny that the 'click to toggle' button used to collapse and expand dashboard meta boxes has stopped working on all admin pages.

I have not found any Javascript or PHP errors related to this, and there is no indication in the AJAX request/response of an issue either.

The problem is distinctly linked to activating/deactivating the Sunny plugin.

Other points of note are:
- One of the sites has the CloudFlare service disabled (bypass, not pause), the other is actively using it.
- Other common plugins of note include Toolset (wp-types.com) and iThemes security.

**Comment by collinbarrett** [comment]
@thewebists this issue is old, but are you still seeing it? I've been using Sunny for a few months on several sites and haven't seen this issue.

**Comment by thewebists** [comment]
I don't know. The issue stopped me from being able to use the plugin.

I'll give the plugin a go next time I'm setting up a new site and let you know.

**Comment by TangRufus** [comment]
Thanks for reporting!!

This is because I used WordPress `postbox.js` and its `css` incorrectly. 

`postbox.js` is currently removed from `master` branch. 
Not sure whether I will add it back or not for version 2. Keep this issue open until version 2 is shipped.

**Comment by TangRufus** [comment]
Sunny v2 don't use `postbox.js` and its `css` anymore.
