### ISSUE TITLE
Ads in plugin

### ISSUE THREAD

**Issue by JayHoltslander** [TypistTech/sunny#127]
Finding these ads in all of my client's websites now.
![](http://take.ms/Ut4LNN)
Not cool! (Competing with my web services and looks unprofessional.)

**Comment by TangRufus** [comment]
You can remove/replace [them](https://github.com/TypistTech/sunny/tree/master/src/Ads) via Sunny's container.

Will I make a ad remover add-on?
Maybe. Not in priority.

**Comment by TangRufus** [comment]
Did you find any implementation flaws inside Sunny, @JayHoltslander?

Related: #135
