### ISSUE TITLE
Review admin notices implementation

### ISSUE THREAD

**Issue by TangRufus** [TypistTech/sunny#135]
Increasing amount of emails / support tickets / 1-star reviews about admin notices won't dismissible. None of them provide useful information to debug or any proof that Sunny is the culprit.

Know issues, when these happens, they break `Sunny`
* Database query caches not purged when updated
* Object cache expire time too long
* Cloudflare is caching `wp-admin`

In my opinion, none of the above is caused by `Sunny` and none of them should be fixed by `Sunny`.

---

Do the admin notices dismissible on your sites, @lukecav, @spieglio, @2aces, @silverbackstudio, @samrathore?

---

Related: #127

**Comment by spieglio** [comment]
Dismissing admin notifications works for me on my installations.
