### ISSUE TITLE
Cron job

### ISSUE THREAD

**Issue by studiosx** [typisttech/sunny#137]
I've scheduled some posts. None of them was published. (Missed schedule)

From cronjob I got this error:
<b>Parse error</b>:  syntax error, unexpected ':', expecting '{' in <b>/home/xxxxx/public_html/wp-content/plugins/sunny-purge-extra-urls-example-master/sunny-purge-extra-urls-example.php</b> on line <b>48</b><br />

Can you hemp me with that issue?
Thank you!

PS: After I deactivated Sunny Purge Extra URLs Example plugin, I got this error from cronjob:
<br />
<b>Parse error</b>:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) in <b>/home/xxxxx/public_html/wp-content/plugins/sunny/src/Sunny.php</b> on line <b>57</b><br />

**Comment by tangrufus** [comment]
Your cron jobs are running on a different PHP version. Sunny requires PHP 7.0 (next release will be 7.1)

If you trigger wp cron via wp cli, see: ~~~https://github.com/TypistTech/sunny/issues/137~~~ https://github.com/TypistTech/wp-cloudflare-guard/issues/74

If you trigger wp cron via `php /home/xxxxx/public_html/wp-cron.php?doing_wp_cron`, then use `/full/path/to/php /home/xxxxx/public_html/wp-cron.php?doing_wp_cron`

Side note: `sunny-purge-extra-urls-example` is an **example**. By default, it doesn't do anything useful.

**Comment by studiosx** [comment]
Thank you very much!
I made the changes and now it works like a charm!

**Comment by tangrufus** [comment]
Glad to help.

For anyone from the future, if you trigger wp cron via wp cli, see: ~~~https://github.com/TypistTech/sunny/issues/137~~~ https://github.com/TypistTech/wp-cloudflare-guard/issues/74
The original link was incorrect.
