### ISSUE TITLE
How does sunny work with HHVM?

### ISSUE THREAD

**Issue by danghaitrieu91** [typisttech/sunny#138]
Hello,

I use easyengine for website. HHVM + Redis + Cloudflare.

Is there any way for Sunny to work with HHVM?

Thanks

**Comment by tangrufus** [comment]
Never tried installing Sunny on HHVM. Currently, no plan to add HHVM support. 

Just curious, with PHP 7.2, does HHVM still faster than normal PHP?

**Comment by danghaitrieu91** [comment]
On my website! HHVM seems still superior in speed :)
