### ISSUE TITLE
Hide Cloudflare email, api key and zone id if set via constants

### ISSUE THREAD

**Issue by TangRufus** [TypistTech/sunny#17]
wait for 
- TypistTech/wp-better-settings#67
- TypistTech/wp-better-settings#78
- TypistTech/wp-better-settings#95

**Comment by fagiani** [comment]
@TangRufus any chance this can be revisited?

**Comment by tangrufus** [comment]
Although undocumented, you can now set Cloudflare email, api key and zone id via constants:

```php
define('SUNNY_CLOUDFLARE_EMAIL', 'you@example.com');
define('SUNNY_CLOUDFLARE_API_KEY', 'aabbcc');
define('SUNNY_CLOUDFLARE_ZONE_ID', 'xxyyzz');
```

Once you defined the constants, the settings page on wp-admin becomes useless.
You can hide it the settings page by using `remove_submenu_page` or `remove_menu_page`. (This part won't be added into Sunny)
