### ISSUE TITLE
warning in uninstall.php

### ISSUE THREAD

**Issue by collinbarrett** [TypistTech/sunny#4]
When uninstalling the plugin via wp-cli:

Warning: in_array() expects parameter 2 to be an array or collection in .../wp-content/plugins/sunny/uninstall.php on line 46

**Comment by TangRufus** [comment]
The new `uninstall.php` checks for `WP_UNINSTALL_PLUGIN` constant instead of `$_REQUEST`. `in_array` calls are removed.
This will be shipped with version 2.0.0 release.

**Comment by TangRufus** [comment]
Thanks for reporting.
