### ISSUE TITLE
Cloudflare API v4

### ISSUE THREAD

**Issue by hasandz** [TypistTech/sunny#6]
I just want to check that, is this project still maintained? 

Cloudflare old API will be deprecated. If this plugin won't receive any update for the new v4 API, all users of the plugin experience problems and unable to connect to the service.

> Notice:
> CloudFlare is removing support for this API on November 9th, 2016. Please use CloudFlare’s API v4 instead. Documentation is available at api.cloudflare.com
> https://www.cloudflare.com/docs/client-api.html

**Comment by hasandz** [comment]
Cloudflare now released a new improved plugin: https://www.cloudflare.com/wordpress/

**Comment by TangRufus** [comment]
this project is deprecated. Use cloudflare's official plugin instead

**Comment by josenobile** [comment]
Hello @TangRufus, take in account Cloudflare plugin for Wordpress still in a very unstable phase. Check the comments in their post announcement: https://blog.cloudflare.com/new-wordpress-plugin/#comment-2906334717

**Comment by josenobile** [comment]
Hello, for example it does not support the cache everything setting (purge post on update, homepage, rss, etc), I have confirmed in the code: https://github.com/silverbackstudio/Cloudflare-WordPress/blob/master/src/WordPress/Hooks.php

**Comment by TangRufus** [comment]
Sunny v2 uses Cloudflare API v4 now.
Note that security functionalities have been separated to [WP Cloudflare Guard](https://wordpress.org/plugins/wp-cloudflare-guard/)
